### ISSUE TITLE
抓取开始后报错 error:  SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by yw981** [sjfkai/grab12306#2]
抓取十几条数据后报错，重复可再现
信息如下
info: 正在抓取车次：D27(北京-->哈尔滨西)   27/8729
info: 正在抓取车次：D28(哈尔滨西-->北京)   28/8729
info: 正在抓取车次：D29(北京-->齐齐哈尔南)   29/8729
info: 正在抓取车次：D30(齐齐哈尔南-->北京)   30/8729
error:  SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at C:\PROJECT\JS\grab12306\lib\grab_schedule.js:54:20
    at tryCatcher (C:\PROJECT\JS\grab12306\node_modules\bluebird\js\main\util.js
:26:23)
    at Promise._settlePromiseFromHandler (C:\PROJECT\JS\grab12306\node_modules\b
luebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\PROJECT\JS\grab12306\node_modules\bluebird\j
s\main\promise.js:584:18)
    at Promise._settlePromises (C:\PROJECT\JS\grab12306\node_modules\bluebird\js
\main\promise.js:700:14)
    at Async._drainQueue (C:\PROJECT\JS\grab12306\node_modules\bluebird\js\main\
async.js:123:16)
    at Async._drainQueues (C:\PROJECT\JS\grab12306\node_modules\bluebird\js\main
\async.js:133:10)
    at Immediate.Async.drainQueues (C:\PROJECT\JS\grab12306\node_modules\bluebir
d\js\main\async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

**Comment by sjfkai** [comment]
fixed
