### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by miaomiaokang** [sjfkai/grab12306#7]
新错误
error:  Error: connect ETIMEDOUT 113.107.44.234:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

**Comment by LIKP0** [comment]
请问这个问题怎么解决？
