### ISSUE TITLE
抓取报错，无法获取车次列表了

### ISSUE THREAD

**Issue by yw981** [sjfkai/grab12306#8]
info: analyse 2749 stations complete....
info: 开始抓取车次列表
downloading [---------------------------------------------------------] 0% 0.0s
downloading [-----------------------------------------------------] 0% 20906.7s
error:  Error: download https://kyfw.12306.cn/otn/resources/js/query/train_list.
js faild
    at Request.<anonymous> (C:\PROJECT\JS\grab12306\node_modules\progress-reques
t\index.js:57:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\PROJECT\JS\grab12306\node_modules\request
\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by sjfkai** [comment]
请检查一下自己的网络 我刚刚访问
 https://kyfw.12306.cn/otn/resources/js/query/train_list.js
是没问题的
